blank_issues_enabled: false
contact_links:
  - name: ğŸ“¦ RefArch - Templates
    url: https://github.com/it-at-m/refarch-templates/issues/new/choose
    about: Open an issue in refarch-templates if the topic is related to code of the templates
  - name: ğŸ’¡ Discussions - Ideas
    url: https://github.com/it-at-m/refarch/discussions/categories/ideas
    about: Feel free to share ideas for the project that are to vague to create a dedicated issue beforehand
  - name: â‰ Discussions - Q&A
    url: https://github.com/it-at-m/refarch/discussions/categories/q-a
    about: Please ask questions here
  - name: ğŸ—¨ Discussions - General
    url: https://github.com/it-at-m/refarch/discussions/categories/general
    about: Discuss more general topics here
