name: release

on:
  workflow_dispatch:
    inputs:
      snapshot-release:
        description: 'Snapshot release?'
        type: boolean
        default: false
      release-version:
        description: 'Release version'
        type: string
        required: true
        default: "X.Y.Z"
      next-version:
        description: "Next version to use after release."
        type: string
        required: true
        default: "X.Y.Z-SNAPSHOT"

jobs:
  build:
    uses: ./.github/workflows/maven.yaml
    with:
      snapshot-release: ${{ inputs.snapshot-release != false }}
      build-images: true
      release-version: ${{ inputs.release-version }}
    secrets: inherit

#  create-github-release:
#    if: ${{ inputs.snapshot-release == false }}
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Create GitHub Release
#        id: create_release
#        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
#        with:
#          tag_name: ${{ github.event.inputs.release-version }}
#          draft: false
#          prerelease: false
#          generate_release_notes: true
